# Generated by Django 5.0.6 on 2024-06-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_plantenvironment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantanalysis",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
    ]
