# Generated by Django 5.0.6 on 2024-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_plantanalysis_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantanalysis",
            name="current_status",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="plantanalysis",
            name="improvement_plan",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="plantanalysis",
            name="plant_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="plantanalysis",
            name="predicted_disease",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="plantanalysis",
            name="risk_level",
            field=models.IntegerField(null=True),
        ),
    ]
