# Generated by Django 5.0.6 on 2024-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_type", models.CharField(max_length=255)),
                ("predicted_disease", models.CharField(max_length=255)),
                ("risk_level", models.IntegerField()),
                ("current_status", models.CharField(max_length=255)),
                ("improvement_plan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlantEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("temperature", models.IntegerField()),
                ("humidity", models.IntegerField()),
                ("illumination", models.IntegerField()),
            ],
        ),
    ]
