# Generated by Django 5.0.6 on 2024-06-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantanalysis",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="plantenvironment",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="plantenvironment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
