# Generated by Django 5.0.6 on 2024-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_plantanalysis_bbox_left_top_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantanalysis",
            name="skip_processing",
            field=models.BooleanField(default=False),
        ),
    ]
